import type {
  LotteryResult,
  LotteryState,
  SavedRecipient,
  TopUpCarrier,
  TopUpOrder,
  TopUpProduct,
} from './types';

export const lotteryStates: LotteryState[] = [
  'Florida',
  'New York',
  'Georgia',
  'New Jersey',
  'Tennessee',
];

export const latestResults: LotteryResult[] = [
  {
    id: 'fl-p3-1',
    state: 'Florida',
    game: 'Pick 3',
    draw: 'Evening',
    date: '2026-07-03',
    winningNumbers: ['4', '1', '9'],
  },
  {
    id: 'fl-p4-1',
    state: 'Florida',
    game: 'Pick 4',
    draw: 'Evening',
    date: '2026-07-03',
    winningNumbers: ['2', '8', '6', '1'],
  },
  {
    id: 'ny-p3-1',
    state: 'New York',
    game: 'Pick 3',
    draw: 'Midday',
    date: '2026-07-03',
    winningNumbers: ['0', '7', '3'],
  },
  {
    id: 'ga-p4-1',
    state: 'Georgia',
    game: 'Pick 4',
    draw: 'Midday',
    date: '2026-07-02',
    winningNumbers: ['1', '5', '9', '4'],
  },
];

export const historyResults: LotteryResult[] = [
  ...latestResults,
  {
    id: 'nj-p3-1',
    state: 'New Jersey',
    game: 'Pick 3',
    draw: 'Evening',
    date: '2026-07-02',
    winningNumbers: ['8', '2', '0'],
  },
  {
    id: 'tn-p4-1',
    state: 'Tennessee',
    game: 'Pick 4',
    draw: 'Evening',
    date: '2026-07-01',
    winningNumbers: ['6', '3', '1', '7'],
  },
  {
    id: 'fl-p3-2',
    state: 'Florida',
    game: 'Pick 3',
    draw: 'Midday',
    date: '2026-07-01',
    winningNumbers: ['5', '4', '0'],
  },
  {
    id: 'ny-p4-1',
    state: 'New York',
    game: 'Pick 4',
    draw: 'Evening',
    date: '2026-06-30',
    winningNumbers: ['9', '9', '2', '4'],
  },
];

export const topUpProducts: TopUpProduct[] = [
  {
    id: 'digicel-airtime-5',
    carrier: 'Digicel',
    productType: 'airtime',
    active: true,
    name: 'Digicel Airtime $5',
    bundleLabel: null,
    amountUsd: 5,
    serviceFeeUsd: 1.49,
    totalUsd: 6.49,
    label: '$5',
    price: 5,
    serviceFee: 1.49,
  },
  {
    id: 'digicel-airtime-10',
    carrier: 'Digicel',
    productType: 'airtime',
    active: true,
    name: 'Digicel Airtime $10',
    bundleLabel: null,
    amountUsd: 10,
    serviceFeeUsd: 1.99,
    totalUsd: 11.99,
    label: '$10',
    price: 10,
    serviceFee: 1.99,
  },
  {
    id: 'digicel-airtime-20',
    carrier: 'Digicel',
    productType: 'airtime',
    active: true,
    name: 'Digicel Airtime $20',
    bundleLabel: null,
    amountUsd: 20,
    serviceFeeUsd: 2.99,
    totalUsd: 22.99,
    label: '$20',
    price: 20,
    serviceFee: 2.99,
  },
  {
    id: 'digicel-airtime-50',
    carrier: 'Digicel',
    productType: 'airtime',
    active: true,
    name: 'Digicel Airtime $50',
    bundleLabel: null,
    amountUsd: 50,
    serviceFeeUsd: 4.99,
    totalUsd: 54.99,
    label: '$50',
    price: 50,
    serviceFee: 4.99,
  },
  {
    id: 'natcom-airtime-5',
    carrier: 'Natcom',
    productType: 'airtime',
    active: true,
    name: 'Natcom Airtime $5',
    bundleLabel: null,
    amountUsd: 5,
    serviceFeeUsd: 1.49,
    totalUsd: 6.49,
    label: '$5',
    price: 5,
    serviceFee: 1.49,
  },
  {
    id: 'natcom-airtime-10',
    carrier: 'Natcom',
    productType: 'airtime',
    active: true,
    name: 'Natcom Airtime $10',
    bundleLabel: null,
    amountUsd: 10,
    serviceFeeUsd: 1.99,
    totalUsd: 11.99,
    label: '$10',
    price: 10,
    serviceFee: 1.99,
  },
  {
    id: 'natcom-airtime-20',
    carrier: 'Natcom',
    productType: 'airtime',
    active: true,
    name: 'Natcom Airtime $20',
    bundleLabel: null,
    amountUsd: 20,
    serviceFeeUsd: 2.99,
    totalUsd: 22.99,
    label: '$20',
    price: 20,
    serviceFee: 2.99,
  },
  {
    id: 'natcom-airtime-50',
    carrier: 'Natcom',
    productType: 'airtime',
    active: true,
    name: 'Natcom Airtime $50',
    bundleLabel: null,
    amountUsd: 50,
    serviceFeeUsd: 4.99,
    totalUsd: 54.99,
    label: '$50',
    price: 50,
    serviceFee: 4.99,
  },
  {
    id: 'digicel-bundle-1975',
    carrier: 'Digicel',
    productType: 'data',
    active: true,
    name: 'Digicel 7-Day Prepaid Plan',
    bundleLabel: '7GB / 7 days',
    amountUsd: 5,
    serviceFeeUsd: 1.49,
    totalUsd: 6.49,
    label: '7GB / 7 days',
    price: 5,
    serviceFee: 1.49,
  },
  {
    id: 'digicel-bundle-58256',
    carrier: 'Digicel',
    productType: 'data',
    active: true,
    name: 'Digicel 7-Day PaleNet Extra',
    bundleLabel: '20GB / 7 days',
    amountUsd: 15,
    serviceFeeUsd: 1.99,
    totalUsd: 16.99,
    label: '20GB / 7 days',
    price: 15,
    serviceFee: 1.99,
  },
  {
    id: 'digicel-bundle-58254',
    carrier: 'Digicel',
    productType: 'data',
    active: true,
    name: 'Digicel 15-Day Stay Connected Plan',
    bundleLabel: '12GB / 15 days',
    amountUsd: 20,
    serviceFeeUsd: 2.99,
    totalUsd: 22.99,
    label: '12GB / 15 days',
    price: 20,
    serviceFee: 2.99,
  },
  {
    id: 'digicel-bundle-58255',
    carrier: 'Digicel',
    productType: 'data',
    active: true,
    name: 'Digicel 30-Day Prepaid Plan',
    bundleLabel: 'Unlimited data / 30 days',
    amountUsd: 24,
    serviceFeeUsd: 2.99,
    totalUsd: 26.99,
    label: 'Unlimited data / 30 days',
    price: 24,
    serviceFee: 2.99,
  },
  {
    id: 'digicel-bundle-58253',
    carrier: 'Digicel',
    productType: 'data',
    active: true,
    name: 'Digicel 30-Day Stay Connected Plan',
    bundleLabel: '16GB / 30 days',
    amountUsd: 25,
    serviceFeeUsd: 2.99,
    totalUsd: 27.99,
    label: '16GB / 30 days',
    price: 25,
    serviceFee: 2.99,
  },
  {
    id: 'natcom-bundle-30165',
    carrier: 'Natcom',
    productType: 'data',
    active: true,
    name: 'Natcom 30GB + 110 Minutes / 15 Days',
    bundleLabel: '30GB + 110 minutes / 15 days',
    amountUsd: 10,
    serviceFeeUsd: 1.99,
    totalUsd: 11.99,
    label: '30GB + 110 minutes / 15 days',
    price: 10,
    serviceFee: 1.99,
  },
  {
    id: 'natcom-bundle-30166',
    carrier: 'Natcom',
    productType: 'data',
    active: true,
    name: 'Natcom 60GB + 220 Minutes / 30 Days',
    bundleLabel: '60GB + 220 minutes / 30 days',
    amountUsd: 20,
    serviceFeeUsd: 2.99,
    totalUsd: 22.99,
    label: '60GB + 220 minutes / 30 days',
    price: 20,
    serviceFee: 2.99,
  },
  {
    id: 'natcom-bundle-58222',
    carrier: 'Natcom',
    productType: 'data',
    active: true,
    name: 'Natcom 90GB + 330 Minutes / 30 Days',
    bundleLabel: '90GB + 330 minutes / 30 days',
    amountUsd: 30,
    serviceFeeUsd: 3.99,
    totalUsd: 33.99,
    label: '90GB + 330 minutes / 30 days',
    price: 30,
    serviceFee: 3.99,
  },
  {
    id: 'natcom-bundle-58221',
    carrier: 'Natcom',
    productType: 'data',
    active: true,
    name: 'Natcom 200GB + Unlimited Minutes / 30 Days',
    bundleLabel: '200GB + unlimited minutes / 30 days',
    amountUsd: 50,
    serviceFeeUsd: 4.99,
    totalUsd: 54.99,
    label: '200GB + unlimited minutes / 30 days',
    price: 50,
    serviceFee: 4.99,
  },
];

export const savedRecipients: SavedRecipient[] = [
  {
    id: 'rec-1',
    name: 'Mika',
    carrier: 'Digicel',
    phoneNumber: '(509) 34-12-44-11',
  },
  {
    id: 'rec-2',
    name: 'Jean',
    carrier: 'Natcom',
    phoneNumber: '(509) 35-89-10-07',
  },
  {
    id: 'rec-3',
    name: 'Aline',
    carrier: 'Digicel',
    phoneNumber: '(509) 33-01-77-22',
  },
];

export const topUpOrders: TopUpOrder[] = [
  {
    id: 'ord-1',
    carrier: 'Digicel',
    productType: 'airtime',
    productLabel: '$20',
    phoneNumber: '(509) 34-12-44-11',
    price: 20,
    serviceFee: 1.99,
    total: 21.99,
    status: 'Pending',
    createdAt: '2026-07-03',
  },
  {
    id: 'ord-2',
    carrier: 'Natcom',
    productType: 'data',
    productLabel: '3GB',
    phoneNumber: '(509) 35-89-10-07',
    price: 12,
    serviceFee: 1.49,
    total: 13.49,
    status: 'Delivered',
    createdAt: '2026-07-01',
  },
];

export const preferredLotteryState: LotteryState = 'Florida';

export const carrierCopy: Record<TopUpCarrier, string> = {
  Digicel: 'Strong coverage across Haiti',
  Natcom: 'Reliable choice for quick airtime',
};
